# Generated by Django 3.1.1 on 2020-10-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='offer',
            new_name='order',
        ),
    ]
