# Generated by Django 3.1.1 on 2020-11-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='writer',
            new_name='writer_details',
        ),
    ]
