# Generated by Django 3.0.3 on 2020-10-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='photo',
        ),
    ]
