# Generated by Django 3.0.3 on 2020-10-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0002_remove_bid_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
