# Generated by Django 3.1.1 on 2020-11-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0002_auto_20201108_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writerimage',
            name='writer',
        ),
        migrations.AddField(
            model_name='writer',
            name='completed_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writer',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='writer.writerimage'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='worker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='writer.writer'),
        ),
    ]
