# Generated by Django 3.1.1 on 2020-10-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0003_writerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
