# Generated by Django 3.1.1 on 2020-11-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0003_auto_20201110_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='photo',
            field=models.ImageField(null=True, unique=True, upload_to='pisarz'),
        ),
    ]
