# Generated by Django 3.1.1 on 2020-11-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0004_auto_20201110_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WriterImage',
        ),
    ]
