# Generated by Django 3.1.1 on 2020-11-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0005_delete_writerimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='completed_order',
            new_name='completed_orders',
        ),
        migrations.AddField(
            model_name='writer',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
