# Generated by Django 3.1.1 on 2020-11-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0007_writer_mini_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='mini_photo',
            field=models.ImageField(default='', null=True, upload_to='pisarz'),
        ),
    ]
