# Generated by Django 3.1.1 on 2020-10-26 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(choices=[('ESE', 'Esej'), ('WYP', 'Wypracowanie')], default='ESE', max_length=3)),
                ('category', models.CharField(choices=[('PRZ', 'Nauki przyrodnicze'), ('HUM', 'Nauki humanistyczne'), ('ŚCI', 'Nauki ścisłe')], default='', max_length=3)),
                ('topic', models.CharField(default='', max_length=100)),
                ('pages', models.IntegerField(default=1)),
                ('deadline', models.DateField()),
                ('instructions', models.CharField(default='', max_length=200)),
                ('attachment', models.FileField(null=True, unique=True, upload_to='attachments')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('value', models.IntegerField(default=0)),
                ('completed_order', models.FileField(null=True, unique=True, upload_to='completed')),
                ('date_completed', models.DateField(null=True)),
                ('assigned_writer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.order')),
            ],
        ),
    ]
