# Generated by Django 3.1.1 on 2020-10-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.CharField(default='', max_length=200),
        ),
    ]
